### ISSUE TITLE
CHANGELOG.md is imprecise on/after v0.6.5

### ISSUE THREAD

**Issue by japaric** [rust-embedded/cortex-m#326]
Due to the semver trick (was that the name?) v0.6.5, and later v0.6.x releases, depend on v0.7.x. This means that if you use v0.6.5 you may observe changes in behavior introduced in the v0.7.x line. The changelog doesn't mention which API may be subject to these changes in behavior (e.g. see #325 ), i.e. which API are re-exported from v0.7.x.

(On a side note, the semver trick also makes it harder to pin a cortex-m version in Cargo.toml, e.g.

``` toml
[dependencies]
cortex-m = "=0.6.5" // pin cortex-m dependency (?)
```
this will not pin the cortex-m v0.7.x dependency so you may still get v0.7.0 or v0.7.1)
