### ISSUE TITLE
master branch out of date 

### ISSUE THREAD

**Issue by perlindgren** [rust-embedded/cortex-m#452]
It seems that the `master` branch is at an older 0.7.4 code.

``` toml
[package]
authors = [
    "The Cortex-M Team <cortex-m@teams.rust-embedded.org>",
    "Jorge Aparicio <jorge@japaric.io>",
]
categories = ["embedded", "hardware-support", "no-std"]
description = "Low level access to Cortex-M processors"
documentation = "https://docs.rs/cortex-m"
keywords = ["arm", "cortex-m", "register", "peripheral"]
license = "MIT OR Apache-2.0"
name = "cortex-m"
readme = "README.md"
repository = "https://github.com/rust-embedded/cortex-m"
version = "0.7.4"
```

Not sure if there is a reason for it. Normally you would expect `master` to either reflect the latest released version or the current development (post release). Its not a huge thing, rather just confusing.

/Per
